# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
deploymentLabel: accounts

replicaCount: 1

image:
  repository: tudux/accounts
  tag: latest

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

config_enabled: true
profile_enabled: true
eureka_enabled: true