# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 1

image:
  repository: tudux/loans
  tag: latest

containerPort: 9000

service:
  type: LoadBalancer
  port: 9000
  targetPort: 9000

config_enabled: true
profile_enabled: true
eureka_enabled: true